apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        ports:
        - containerPort: 8888
        image: wil42/playground:v1

---
apiVersion: v1
kind: NodePort
metadata:
  name: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
  - name: wil-playground
    protocol: TCP
    port: 80
    targetPort: 8888
    nodePort: 8888
